version: '3'

services:
  mysql:
    image: mysql:5.7.18
    container_name: pokedex-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "p4ssw0r#"
      MYSQL_DATABASE: "pokedex"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - pokedex-net
    ports:
      - "3306:3306"

  pokedex.webapi:
    image: pokedex.webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - pokedex-net
volumes:
  mysql-data:
networks:
  pokedex-net:
    driver: bridge