version: '3.3'

services:
    db:
        image: database
        build:
          context: ./
          dockerfile: DatabaseDockerfile
        ports:
          - "1433:1433"
        environment:
          SA_PASSWORD: "Alaska2017"
          ACCEPT_EULA: "Y"
        healthcheck:
          test: sqlcmd -S dev.network.com -U SA -P 'Alaska2017' -Q 'select 1'
        networks:
          - pokedex-net
          
    migrator:
        image: migrator
        build:
          context: ./
          dockerfile: MigratorDockerfile
        depends_on:
          - db
        links:
          - db
        networks:
            - pokedex-net
                     
    webapi:
        image: webapi
        build:
          context: ./
          dockerfile: WebapiDockerfile
        ports:
          - "5000:80"
        depends_on:
          - db
        links:
          - db
        networks:
          - pokedex-net
      
networks:
  pokedex-net:
    driver: bridge